CREATE DATABASE [TALab]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TALab_Data', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\TALab_Data.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TALab_log', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\TALab_Log.ldf' , SIZE = 73728KB , FILEGROWTH = 65536KB )
GO


BACKUP DATABASE TALab TO DISK='TALab.BAK' WITH STATS =5

CREATE TABLE MYLAB01 (LabName varchar(50))

BACKUP LOG TALab TO DISK='TALab01.TRN' 



RESTORE DATABASE TALab FROM DISK='TALab.BAK' WITH STATS =5, NORECOVERY

RESTORE LOG TALab FROM DISK='TALab.BAK' WITH STATS =5, RECOVERY

USE TALab

Select * from MYLAB01
